language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-27

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/

script:
  - chmod u+x gradlew
  - ./gradlew clean
  - ./gradlew build
